name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-asyncio black isort
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    
    - name: Check formatting with Black
      run: |
        black . --check
    
    - name: Check import sorting with isort
      run: |
        isort . --check-only --profile black
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude="draft_scripts,venv" --per-file-ignores="tests/*:F401,F841 utils.py:F401 main.py:C901 models.py:C901,F401 providers/*:C901"
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude="draft_scripts,venv" --per-file-ignores="tests/*:F401,F841 utils.py:F401 main.py:C901 models.py:C901,F401 providers/*:C901"
    
    - name: Run unit tests
      run: |
        pytest tests/ -v -m "not integration and not playwright"
